version: '3.9'

services:
  db:
    image: mariadb:10.11
    container_name: kogo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kogo
      MYSQL_USER: kogo
      MYSQL_PASSWORD: kogo123
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-fpm
    container_name: kogo-wp
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: kogo
      WORDPRESS_DB_USER: kogo
      WORDPRESS_DB_PASSWORD: kogo123
    volumes:
      - ./wp:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: kogo-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./wp:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kogo-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ABSOLUTE_URI: http://localhost:8081/
    depends_on:
      - db
